services:
  dev:
    build: .
    image: dev-setup
    volumes:
      - ${SSH_AUTH_SOCK}:/tmp/ssh-agent.sock
    environment:
      - SSH_AUTH_SOCK=/tmp/ssh-agent.sock
      - GITHUB_USERNAME=girts521
    # network_mode: host
    stdin_open: true
    tty: true

