services:
  dev:
    build: .
    image: dev
    volumes:
      - /home/girts/Documents:/home/devuser/Documents
      - /home/girts/Desktop:/home/devuser/Desktop
      - /home/girts/Downloads:/home/devuser/Downloads
    stdin_open: true
    tty: true

